/// The brainpoolP384r1 elliptic curve, RFC 5639 section 3.6.
///
/// The domain parameters live in `BrainpoolP384r1Values` as limb literals;
/// this type gives them curve meaning and provides scalar multiplication.
/// PACE on the FINEID card uses this curve for the ephemeral key agreement
/// and the generic mapping, and CryptoKit offers no Brainpool curve, so the
/// arithmetic is ours.
///
/// Scalar multiplication is double-and-add and is not constant-time. The
/// scalars it consumes are the ephemeral, single-use PACE keys, matching the
/// stated posture of the Rust reference implementation; it must not be given
/// a long-lived private key.
///
/// Provenance: lifted from the ReFineID iOS browser donor
/// `Sources/ReFineIDBrowserKit/Crypto/BrainpoolP384.swift`.
public enum BrainpoolP384r1 {
  /// The field prime `p`.
  internal static let prime = BrainpoolP384r1Values.prime

  /// The curve equation coefficient `A`, as a field element.
  internal static let coefficientA = FieldP384(BrainpoolP384r1Values.coefficientA)

  /// The curve equation coefficient `B`, as a field element.
  internal static let coefficientB = FieldP384(BrainpoolP384r1Values.coefficientB)

  /// The base point `G`.
  public static let generator = BrainpoolPoint(
    onCurveX: BrainpoolP384r1Values.generatorX,
    onCurveY: BrainpoolP384r1Values.generatorY
  )

  /// The order `n` of the subgroup generated by `G`.
  public static let order = BrainpoolP384r1Values.order

  /// The cofactor `h`, which is 1 for this curve.
  public static let cofactor = BrainpoolP384r1Values.cofactor

  /// `scalar * point`, by double-and-add from the scalar's highest set bit.
  ///
  /// A zero scalar gives the point at infinity.
  public static func multiply(_ point: BrainpoolPoint, by scalar: U384) -> BrainpoolPoint {
    guard let highestBit = scalar.highestSetBitIndex else { return .infinity }
    var result = BrainpoolPoint.infinity
    for index in stride(from: highestBit, through: 0, by: -1) {
      result = result.doubled()
      if scalar.bit(at: index) {
        result = result.adding(point)
      }
    }
    return result
  }

  /// `scalar * G`, the public point of a private scalar.
  public static func multiplyGenerator(by scalar: U384) -> BrainpoolPoint {
    multiply(Self.generator, by: scalar)
  }
}
