// Copyright 2026 Petri Koistinen. Licensed under the Apache License, Version 2.0.

/// The dedicated home for the brainpoolP384r1 domain parameters.
///
/// RFC 5639 section 3.6 publishes these as big-endian hex strings. They are
/// transcribed here exactly once, as little-endian 64-bit limb literals in
/// the layout `U384` stores, so no hex parser exists at runtime and nothing
/// in the curve code has a parse result to force-unwrap. Each limb is a named
/// binding, in order from least to most significant.
///
/// The transcription is checked mechanically by `BrainpoolP384r1Tests`: the
/// generator's SEC1 encoding is compared against the RFC's big-endian hex,
/// the generator satisfies the curve equation, and `n * G` is the point at
/// infinity. No wrong limb survives all three.
///
/// Provenance: lifted from the RefineID iOS browser donor
/// `Sources/RefineIDBrowserKit/Crypto/BrainpoolP384.swift` and
/// `Sources/RefineIDBrowserKit/Crypto/FieldP384.swift`, whose big-endian hex
/// constants these limbs encode.
internal enum BrainpoolP384r1Values {
  /// The field prime `p`.
  internal static let prime: U384 = {
    let limb0: UInt64 = 0x8747_0013_3107_EC53
    let limb1: UInt64 = 0xACD3_A729_901D_1A71
    let limb2: UInt64 = 0x12B1_DA19_7FB7_1123
    let limb3: UInt64 = 0x152F_7109_ED54_56B4
    let limb4: UInt64 = 0x0F5D_6F7E_50E6_41DF
    let limb5: UInt64 = 0x8CB9_1E82_A338_6D28
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The curve equation coefficient `A` in `y^2 = x^3 + A*x + B`.
  internal static let coefficientA: U384 = {
    let limb0: UInt64 = 0x04A8_C7DD_22CE_2826
    let limb1: UInt64 = 0x8AA5_814A_503A_D4EB
    let limb2: UInt64 = 0x1391_65EF_BA91_F90F
    let limb3: UInt64 = 0xC2BE_A28E_4FB2_2787
    let limb4: UInt64 = 0x3C72_080A_CE05_AFA0
    let limb5: UInt64 = 0x7BC3_82C6_3D8C_150C
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The curve equation coefficient `B` in `y^2 = x^3 + A*x + B`.
  internal static let coefficientB: U384 = {
    let limb0: UInt64 = 0x3AB7_8696_FA50_4C11
    let limb1: UInt64 = 0x7CB4_3902_95DB_C994
    let limb2: UInt64 = 0x2E88_0EA5_3EEB_62D5
    let limb3: UInt64 = 0x2FB7_7DE1_07DC_D2A6
    let limb4: UInt64 = 0x8B39_B554_16F0_447C
    let limb5: UInt64 = 0x04A8_C7DD_22CE_2826
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The `x` coordinate of the base point `G`.
  internal static let generatorX: U384 = {
    let limb0: UInt64 = 0xEF87_B2E2_47D4_AF1E
    let limb1: UInt64 = 0xE826_E034_36D6_46AA
    let limb2: UInt64 = 0xDB7F_CAFE_0CBD_10E8
    let limb3: UInt64 = 0x8847_A3E7_7EF1_4FE3
    let limb4: UInt64 = 0xA2A6_3A81_B7C1_3F6B
    let limb5: UInt64 = 0x1D1C_64F0_68CF_45FF
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The `y` coordinate of the base point `G`.
  internal static let generatorY: U384 = {
    let limb0: UInt64 = 0x4282_0341_263C_5315
    let limb1: UInt64 = 0x0E46_4621_7791_8111
    let limb2: UInt64 = 0xE19C_054F_F991_2928
    let limb3: UInt64 = 0x62B7_0B29_FEEC_5864
    let limb4: UInt64 = 0x5CB1_EB8E_95CF_D552
    let limb5: UInt64 = 0x8ABE_1D75_20F9_C2A4
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The order `n` of the subgroup generated by `G`.
  internal static let order: U384 = {
    let limb0: UInt64 = 0x3B88_3202_E904_6565
    let limb1: UInt64 = 0xCF3A_B6AF_6B7F_C310
    let limb2: UInt64 = 0x1F16_6E6C_AC04_25A7
    let limb3: UInt64 = 0x152F_7109_ED54_56B3
    let limb4: UInt64 = 0x0F5D_6F7E_50E6_41DF
    let limb5: UInt64 = 0x8CB9_1E82_A338_6D28
    return U384(
      limb0: limb0,
      limb1: limb1,
      limb2: limb2,
      limb3: limb3,
      limb4: limb4,
      limb5: limb5
    )
  }()

  /// The cofactor `h`, which RFC 5639 fixes at 1 for this curve.
  ///
  /// A cofactor of 1 means the curve group and the prime-order subgroup
  /// coincide, so a point that is on the curve and not at infinity is
  /// automatically in the subgroup.
  internal static let cofactor: UInt64 = 1
}
